/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomescreenRouteImport } from './routes/_homescreen'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomescreenClipboardRouteImport } from './routes/_homescreen/clipboard'

const HomescreenRoute = HomescreenRouteImport.update({
  id: '/_homescreen',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomescreenClipboardRoute = HomescreenClipboardRouteImport.update({
  id: '/clipboard',
  path: '/clipboard',
  getParentRoute: () => HomescreenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/clipboard': typeof HomescreenClipboardRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/clipboard': typeof HomescreenClipboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_homescreen': typeof HomescreenRouteWithChildren
  '/login': typeof LoginRoute
  '/_homescreen/clipboard': typeof HomescreenClipboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/clipboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/clipboard'
  id: '__root__' | '/_homescreen' | '/login' | '/_homescreen/clipboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomescreenRoute: typeof HomescreenRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_homescreen': {
      id: '/_homescreen'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomescreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_homescreen/clipboard': {
      id: '/_homescreen/clipboard'
      path: '/clipboard'
      fullPath: '/clipboard'
      preLoaderRoute: typeof HomescreenClipboardRouteImport
      parentRoute: typeof HomescreenRoute
    }
  }
}

interface HomescreenRouteChildren {
  HomescreenClipboardRoute: typeof HomescreenClipboardRoute
}

const HomescreenRouteChildren: HomescreenRouteChildren = {
  HomescreenClipboardRoute: HomescreenClipboardRoute,
}

const HomescreenRouteWithChildren = HomescreenRoute._addFileChildren(
  HomescreenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  HomescreenRoute: HomescreenRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
